name: Build ARM

on: [push, pull_request]

jobs:
    build_wheels:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Checkout tools repo
              uses: actions/checkout@v3
              with:
                  repository: ckindermann/tree-sitter-manchester
                  path: tree-sitter-manchester

            - name: Checkout another tools repo  
              uses: actions/checkout@v3
              with:
                  repository: ckindermann/man-parse-rust
                  path: man-parse-rust

            - name: Setup Bindings 
              run: |
                  mv python_module.rs man-parse-rust/src/
                  mv Cargo.toml man-parse-rust/
                  echo "mod python_module;" >> man-parse-rust/src/lib.rs 

            - name: Set up the QEMU static binaries
              uses: docker/setup-qemu-action@v1
              with:
                  platforms: all

            - run: |
                docker run --rm --privileged multiarch/qemu-user-static:register --reset

            - uses: docker://multiarch/ubuntu-core:arm64-bionic
              with:
                  args: 'uname -a'

            - uses: docker://multiarch/ubuntu-core:arm64-bionic
              with:
                  args: >
                      bash -c
                      "apt-get update &&
                      apt-get install -y curl &&
                      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh && 
                      cargo install tree-sitter-cli &&
                      tree-sitter generate &&
                      apt-get install -y python3.6 &&
                      python3.6 --version &&
                      apt-get -y install python3-pip &&
                      pip install -U pip maturin
                      maturin build 
                      ls &&
                      python3.6 -c\"import platform; print(platform.machine())\""


            - name: Download wheel 
              uses: actions/upload-artifact@v3
              with:
                  name: wheel
                  path: man-parse-rust/target/wheels/*.whl
