name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-10.15]
        python-version: ['2.7', '3.7', '3.8']


    steps:
      - uses: actions/checkout@v3

      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
            repository: ckindermann/tree-sitter-manchester
            path: tree-sitter-manchester

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy 

      - uses: actions/setup-python@v3

      - name: Install dependencies
        run: |
            cargo install tree-sitter-cli

      - name: Build parser
        working-directory: tree-sitter-manchester
        run: |
            tree-sitter generate

        #- uses: actions/upload-artifact@v3
        #- with:
        #-   name: ${{ matrix.os }}-${{ matrix.python-version }}
        #-   path: ./dist/*.whl
